/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

import pubsub.Difusor;

/**
 *
 * @author dionatan
 */
public class ClienteView extends javax.swing.JFrame {
	public static Socket s;
	/**
	 * Creates new form ClienteView
	 */
	public ClienteView() {
		initComponents();
		try {
			s = new Socket("localhost", 1972);
                        s.setSoTimeout(1000);
                        ConsumidorThread cst = new ConsumidorThread();
                        cst.start();
		} catch (UnknownHostException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		btnParar1 = new javax.swing.JButton();
		btnParar2 = new javax.swing.JButton();
		btnParar3 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jtaCliente1 = new javax.swing.JTextArea();
		jScrollPane2 = new javax.swing.JScrollPane();
		jtaCliente2 = new javax.swing.JTextArea();
		jScrollPane3 = new javax.swing.JScrollPane();
		jtaCliente3 = new javax.swing.JTextArea();
		jcb1 = new javax.swing.JComboBox();
		jcb12 = new javax.swing.JComboBox();
		jcb3 = new javax.swing.JComboBox();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
		jLabel1.setText("Consumidor");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGap(293, 293, 293)
						.addComponent(jLabel1)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 22, Short.MAX_VALUE))
				);

		btnParar1.setText("Parar");
		btnParar1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnParar1ActionPerformed(evt);
			}
		});

		btnParar2.setText("Parar");

		btnParar3.setText("Parar");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addGap(68, 68, 68)
						.addComponent(btnParar1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(btnParar2)
						.addGap(176, 176, 176)
						.addComponent(btnParar3)
						.addGap(88, 88, 88))
				);
		jPanel2Layout.setVerticalGroup(
				jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnParar1)
								.addComponent(btnParar2)
								.addComponent(btnParar3))
								.addContainerGap(14, Short.MAX_VALUE))
				);

		jtaCliente1.setColumns(20);
		jtaCliente1.setRows(5);
		jScrollPane1.setViewportView(jtaCliente1);

		jtaCliente2.setColumns(20);
		jtaCliente2.setRows(5);
		jScrollPane2.setViewportView(jtaCliente2);

		jtaCliente3.setColumns(20);
		jtaCliente3.setRows(5);
		jScrollPane3.setViewportView(jtaCliente3);

		jcb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um item", "Esportes", "Novidades Internet", "Eletronicos", "Politica", "Negócios ", "Viagens" }));
		jcb1.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				jcb1ItemStateChanged(evt);
			}
		});
		jcb1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jcb1ActionPerformed(evt);
			}
		});

		jcb12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um item", "Esportes", "Novidades Internet", "Eletronicos", "Politica", "Negócios ", "Viagens" }));
		jcb12.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				jcb12ItemStateChanged(evt);
			}
		});

		jcb3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um item", "Esportes", "Novidades Internet", "Eletronicos", "Politica", "Negócios ", "Viagens" }));
		jcb3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jcb3ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addContainerGap())
										.addGroup(layout.createSequentialGroup()
												.addComponent(jcb1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jcb12, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18)
												.addComponent(jcb3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(20, 20, 20))))
												.addGroup(layout.createSequentialGroup()
														.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(0, 12, Short.MAX_VALUE))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jcb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jcb12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jcb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
										.addComponent(jScrollPane1)
										.addComponent(jScrollPane3))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap())
				);

		pack();
	}// </editor-fold>                        

	private void jcb1ActionPerformed(java.awt.event.ActionEvent evt) {                                     
		// TODO add your handling code here:
	}                                    

	private void jcb1ItemStateChanged(java.awt.event.ItemEvent evt) {                                      
		if(jcb1.getSelectedIndex() != 0)
		enviaTCP(jcb1.getSelectedIndex(), 1);
	}                                     

	private void jcb12ItemStateChanged(java.awt.event.ItemEvent evt) {                                       
		if(jcb12.getSelectedIndex() != 0)
		enviaTCP(jcb12.getSelectedIndex(), 2);
	}                                      

	private void jcb3ActionPerformed(java.awt.event.ActionEvent evt) {                                     
		if(jcb3.getSelectedIndex() != 0)
		enviaTCP(jcb3.getSelectedIndex(), 3);
	}                                    
	
	public void enviaTCP(int obj, int panel){
            try {
            ObjectOutputStream esc = new ObjectOutputStream(s.getOutputStream());
            esc.writeObject(obj);
            ObjectInputStream read = new ObjectInputStream(s.getInputStream());
            String info = (String)read.readObject();
            atualizaPanel(info, panel);
            } catch (IOException ex) {
                    Logger.getLogger(ConsumidorThread.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {  
            Logger.getLogger(ClienteView.class.getName()).log(Level.SEVERE, null, ex);
        } 
	}
	
	
	public void atualizaPanel(String info, int panel){
		switch(panel){
		case 1:
			jtaCliente1.setText(info);
			break;
		case 2:
			jtaCliente2.setText(info);
			break;
		case 3:
			jtaCliente3.setText(info);
			break;
		}
	}
	
	private void btnParar1ActionPerformed(java.awt.event.ActionEvent evt) {                                          

	}                                         

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ClienteView().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify                     
	private javax.swing.JButton btnParar1;
	private javax.swing.JButton btnParar2;
	private javax.swing.JButton btnParar3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JComboBox jcb1;
	private javax.swing.JComboBox jcb12;
	private javax.swing.JComboBox jcb3;
	private javax.swing.JTextArea jtaCliente1;
	private javax.swing.JTextArea jtaCliente2;
	private javax.swing.JTextArea jtaCliente3;
	// End of variables declaration                   
}
